### ISSUE TITLE
Mod page has an image in the gallery, but that image is empty

### ISSUE THREAD

**Issue by James103** [5uso/DataReload#2]
The mod page for this mod, Data Reload, has a gallery tab with one image; however, that image is an empty file and won't load.

The image or images should depict an example of a data pack error exposed to the client chat via this mod.

See https://modrinth.com/mod/data-reload/gallery for the error.

**Comment by 5uso** [comment]
Oh, it looks like it must have gone missing at some point, strange. Thanks for pointing it out
